name: Feature
description: Product feature work item
title: "[feat] "
labels: ["feat"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
  - type: textarea
    id: background
    attributes:
      label: Background
  - type: textarea
    id: scope
    attributes:
      label: Scope
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
